### ISSUE TITLE
Xcode Target Dependencies

### ISSUE THREAD

**Issue by jkampitakis** [agens-no/iMessageStickerUnity#30]
Hello,
in order for this plugin to work we must open the Xcode generated project and select "Build Phases" ->  "Target Dependencies" -> "Unity-iPhone-Stickers" target.

https://www.dropbox.com/s/0yshd72o862mem4/Screen%20Shot%202018-07-05%20at%2018.37.11.png?dl=0

Is there a way to automate this process?

Kind regards,
John.

**Comment by PixelEnvision** [comment]
+1,  Would be nice to get this working.

It looks like there is a code in post build script to add this dependency but it's not working for me. Xcode 9.4.1 with Unity 2017.4.8.f1

**Comment by skjalgsm** [comment]
I just merged in a PR that might fix this issue as xcode might not have recognized "iPhone Development" as your code sign identity and it fixed itself automatically when you selected the "Unity-iPhone-Stickers" target. Could you update and check to see if it works now? https://github.com/agens-no/iMessageStickerUnity/pull/31/commits/4c2d8c263d446338a0cce3dd7f654d17deeeaed5

**Comment by jkampitakis** [comment]
We still get the following error:

error: /Users/john/Library/Developer/Xcode/DerivedData/Unity-iPhone-andttpaqhibkcyezyvfjideiywma/Build/Products/ReleaseForRunning-iphoneos/Unity-iPhone-Stickers.appex: No such file or directory

**Comment by skjalgsm** [comment]
I think I found a solution to the problem. It works out of the box for me now on a completely fresh jenkins box using fastlane. What was missing was that TargetAttributes didn't have a reference to the new sticker target and I fixed it by adding a reference to the team id there.

**Comment by firepunchd** [comment]
Hello.
I'm so glad I found this. I've been using your utility for some releases but suddenly I get this xcode error  (also with latest release)
error: /Users/admin/Library/Developer/Xcode/DerivedData/Unity-iPhone-fobzuqujcakeilfyhrzqntkkkfco/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/Unity-iPhone-Stickers.appex: No such file or directory

Do you have any idea how I can research/solve this issue?

Thank you!,
Simon
